table! {
    /// Representation of the `blacklists` table.
    ///
    /// (Automatically generated by Diesel.)
    blacklists (bid) {
        /// The `bid` column of the `blacklists` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        bid -> Int8,
        /// The `uuid_a` column of the `blacklists` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid_a -> Int8,
        /// The `uuid_b` column of the `blacklists` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid_b -> Int8,
        /// The `modify_time` column of the `blacklists` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `blacklists` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `buff_metadatas` table.
    ///
    /// (Automatically generated by Diesel.)
    buff_metadatas (buff_id) {
        /// The `buff_id` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        buff_id -> Int8,
        /// The `name` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `amounts` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        amounts -> Int4,
        /// The `buff_category` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        buff_category -> Int2,
        /// The `buff_type` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        buff_type -> Int2,
        /// The `sub_buff_type` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        sub_buff_type -> Int2,
        /// The `is_show` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        is_show -> Int2,
        /// The `modify_time` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `buff_metadatas` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `chat_groups` table.
    ///
    /// (Automatically generated by Diesel.)
    chat_groups (gid) {
        /// The `gid` column of the `chat_groups` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        gid -> Int8,
        /// The `group_name` column of the `chat_groups` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        group_name -> Varchar,
        /// The `group_thumbnail` column of the `chat_groups` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        group_thumbnail -> Varchar,
        /// The `uuid` column of the `chat_groups` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `person_count` column of the `chat_groups` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        person_count -> Int2,
        /// The `modify_time` column of the `chat_groups` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `chat_groups` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `chat_groups_uids` table.
    ///
    /// (Automatically generated by Diesel.)
    chat_groups_uids (guid) {
        /// The `guid` column of the `chat_groups_uids` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guid -> Int8,
        /// The `gid` column of the `chat_groups_uids` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        gid -> Int8,
        /// The `uuid` column of the `chat_groups_uids` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `latest_timestamp` column of the `chat_groups_uids` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        latest_timestamp -> Int8,
        /// The `unread_count` column of the `chat_groups_uids` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        unread_count -> Int2,
        /// The `modify_time` column of the `chat_groups_uids` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `chat_groups_uids` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `chat_messages` table.
    ///
    /// (Automatically generated by Diesel.)
    chat_messages (mid) {
        /// The `mid` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        mid -> Int8,
        /// The `send_id` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        send_id -> Int8,
        /// The `to_id` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        to_id -> Int8,
        /// The `content` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        content -> Varchar,
        /// The `created_timestamp` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        created_timestamp -> Int8,
        /// The `kind` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Int2,
        /// The `modify_time` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
        /// The `msg_type` column of the `chat_messages` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        msg_type -> Int2,
    }
}

table! {
    /// Representation of the `chat_user_unread_counts` table.
    ///
    /// (Automatically generated by Diesel.)
    chat_user_unread_counts (ucid) {
        /// The `ucid` column of the `chat_user_unread_counts` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        ucid -> Int8,
        /// The `uuid_s` column of the `chat_user_unread_counts` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid_s -> Int8,
        /// The `uuid_d` column of the `chat_user_unread_counts` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid_d -> Int8,
        /// The `latest_timestamp` column of the `chat_user_unread_counts` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        latest_timestamp -> Int8,
        /// The `unread_count` column of the `chat_user_unread_counts` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        unread_count -> Int2,
        /// The `modify_time` column of the `chat_user_unread_counts` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `chat_user_unread_counts` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `enemys` table.
    ///
    /// (Automatically generated by Diesel.)
    enemys (eid) {
        /// The `eid` column of the `enemys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        eid -> Int8,
        /// The `enemy_name` column of the `enemys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        enemy_name -> Varchar,
        /// The `model_path` column of the `enemys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        model_path -> Varchar,
        /// The `thumbnail` column of the `enemys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        thumbnail -> Varchar,
        /// The `max_hp` column of the `enemys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        max_hp -> Int4,
        /// The `attack_power` column of the `enemys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        attack_power -> Int4,
        /// The `move_speed` column of the `enemys` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        move_speed -> Float4,
        /// The `max_mana` column of the `enemys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        max_mana -> Int4,
        /// The `defense` column of the `enemys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        defense -> Int4,
        /// The `animation_hit_delay` column of the `enemys` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        animation_hit_delay -> Float4,
        /// The `spawn_style_class` column of the `enemys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        spawn_style_class -> Varchar,
        /// The `bp_enemy` column of the `enemys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        bp_enemy -> Varchar,
        /// The `ap_enemy` column of the `enemys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        ap_enemy -> Varchar,
        /// The `skm_enemy` column of the `enemys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        skm_enemy -> Varchar,
        /// The `aenemy_die` column of the `enemys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        aenemy_die -> Varchar,
        /// The `modify_time` column of the `enemys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `enemys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `equipment_kinds` table.
    ///
    /// (Automatically generated by Diesel.)
    equipment_kinds (kid) {
        /// The `kid` column of the `equipment_kinds` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        kid -> Int8,
        /// The `name` column of the `equipment_kinds` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `kind` column of the `equipment_kinds` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Int2,
        /// The `modify_time` column of the `equipment_kinds` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `equipment_kinds` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `equipments` table.
    ///
    /// (Automatically generated by Diesel.)
    equipments (eid) {
        /// The `eid` column of the `equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        eid -> Int8,
        /// The `kid` column of the `equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        kid -> Int8,
        /// The `name` column of the `equipments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `thumbnail` column of the `equipments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        thumbnail -> Varchar,
        /// The `price` column of the `equipments` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        price -> Int4,
        /// The `hp` column of the `equipments` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        hp -> Int4,
        /// The `multiplier` column of the `equipments` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        multiplier -> Float4,
        /// The `kind` column of the `equipments` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Int2,
        /// The `is_default` column of the `equipments` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        is_default -> Int2,
        /// The `modify_time` column of the `equipments` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `equipments` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `friends` table.
    ///
    /// (Automatically generated by Diesel.)
    friends (fid) {
        /// The `fid` column of the `friends` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        fid -> Int8,
        /// The `uuid_a` column of the `friends` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid_a -> Int8,
        /// The `uuid_b` column of the `friends` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid_b -> Int8,
        /// The `state` column of the `friends` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        state -> Int2,
        /// The `modify_time` column of the `friends` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `friends` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `gem_relateds` table.
    ///
    /// (Automatically generated by Diesel.)
    gem_relateds (grid) {
        /// The `grid` column of the `gem_relateds` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        grid -> Int8,
        /// The `obj_id` column of the `gem_relateds` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        obj_id -> Int8,
        /// The `gid` column of the `gem_relateds` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        gid -> Int8,
        /// The `obj_type` column of the `gem_relateds` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        obj_type -> Int2,
        /// The `modify_time` column of the `gem_relateds` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `gem_relateds` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `gems` table.
    ///
    /// (Automatically generated by Diesel.)
    gems (gid) {
        /// The `gid` column of the `gems` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        gid -> Int8,
        /// The `gem_icon` column of the `gems` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        gem_icon -> Varchar,
        /// The `gem_selected_material` column of the `gems` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        gem_selected_material -> Varchar,
        /// The `gem_link_material` column of the `gems` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        gem_link_material -> Varchar,
        /// The `model_path` column of the `gems` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        model_path -> Varchar,
        /// The `kind` column of the `gems` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        kind -> Int2,
        /// The `modify_time` column of the `gems` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `gems` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `player_mount_equipments` table.
    ///
    /// (Automatically generated by Diesel.)
    player_mount_equipments (id) {
        /// The `id` column of the `player_mount_equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `pid` column of the `player_mount_equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        pid -> Int8,
        /// The `uid` column of the `player_mount_equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Int8,
        /// The `equipment_id` column of the `player_mount_equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        equipment_id -> Int8,
        /// The `modify_time` column of the `player_mount_equipments` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `player_mount_equipments` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `players` table.
    ///
    /// (Automatically generated by Diesel.)
    players (pid) {
        /// The `pid` column of the `players` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        pid -> Int8,
        /// The `player_name` column of the `players` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        player_name -> Varchar,
        /// The `model_path` column of the `players` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        model_path -> Varchar,
        /// The `thumbnail` column of the `players` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        thumbnail -> Varchar,
        /// The `max_hp` column of the `players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        max_hp -> Int4,
        /// The `attack_power` column of the `players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        attack_power -> Int4,
        /// The `move_speed` column of the `players` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        move_speed -> Float4,
        /// The `max_mana` column of the `players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        max_mana -> Int4,
        /// The `defense` column of the `players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        defense -> Int4,
        /// The `animation_hit_delay` column of the `players` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        animation_hit_delay -> Float4,
        /// The `spawn_style_class` column of the `players` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        spawn_style_class -> Varchar,
        /// The `level` column of the `players` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `star_level` column of the `players` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        star_level -> Int2,
        /// The `level_experience` column of the `players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        level_experience -> Int4,
        /// The `is_default` column of the `players` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        is_default -> Int2,
        /// The `modify_time` column of the `players` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `players` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_action_points_categorys` table.
    ///
    /// (Automatically generated by Diesel.)
    props_action_points_categorys (item_id) {
        /// The `item_id` column of the `props_action_points_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `ap_value` column of the `props_action_points_categorys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        ap_value -> Int4,
        /// The `modify_time` column of the `props_action_points_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_action_points_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_fixed_treasure_chest_category_assets` table.
    ///
    /// (Automatically generated by Diesel.)
    props_fixed_treasure_chest_category_assets (aid) {
        /// The `aid` column of the `props_fixed_treasure_chest_category_assets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        aid -> Int8,
        /// The `item_id` column of the `props_fixed_treasure_chest_category_assets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `sub_item_id` column of the `props_fixed_treasure_chest_category_assets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        sub_item_id -> Int8,
        /// The `amounts` column of the `props_fixed_treasure_chest_category_assets` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        amounts -> Int4,
        /// The `modify_time` column of the `props_fixed_treasure_chest_category_assets` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_fixed_treasure_chest_category_assets` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_fixed_treasure_chest_categorys` table.
    ///
    /// (Automatically generated by Diesel.)
    props_fixed_treasure_chest_categorys (item_id) {
        /// The `item_id` column of the `props_fixed_treasure_chest_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `price` column of the `props_fixed_treasure_chest_categorys` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        price -> Float4,
        /// The `is_instantly_open` column of the `props_fixed_treasure_chest_categorys` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        is_instantly_open -> Int2,
        /// The `option_values` column of the `props_fixed_treasure_chest_categorys` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        option_values -> Int2,
        /// The `modify_time` column of the `props_fixed_treasure_chest_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_fixed_treasure_chest_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_item_metadatas` table.
    ///
    /// (Automatically generated by Diesel.)
    props_item_metadatas (item_id) {
        /// The `item_id` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `name` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `thumbnail` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        thumbnail -> Varchar,
        /// The `description` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Varchar,
        /// The `overlay_status` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        overlay_status -> Int2,
        /// The `sub_item_type` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        sub_item_type -> Int2,
        /// The `bag_type` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        bag_type -> Int2,
        /// The `rarity_type` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        rarity_type -> Int2,
        /// The `modify_time` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_item_metadatas` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_key_categorys` table.
    ///
    /// (Automatically generated by Diesel.)
    props_key_categorys (item_id) {
        /// The `item_id` column of the `props_key_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `chest_item_id` column of the `props_key_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        chest_item_id -> Int8,
        /// The `modify_time` column of the `props_key_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_key_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_mall_assets` table.
    ///
    /// (Automatically generated by Diesel.)
    props_mall_assets (aid) {
        /// The `aid` column of the `props_mall_assets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        aid -> Int8,
        /// The `item_id` column of the `props_mall_assets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `sub_item_id` column of the `props_mall_assets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        sub_item_id -> Int8,
        /// The `amounts` column of the `props_mall_assets` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        amounts -> Int4,
        /// The `modify_time` column of the `props_mall_assets` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_mall_assets` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_malls` table.
    ///
    /// (Automatically generated by Diesel.)
    props_malls (item_id) {
        /// The `item_id` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `next_item_id` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        next_item_id -> Int8,
        /// The `level` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `item_category` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        item_category -> Int2,
        /// The `price` column of the `props_malls` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        price -> Float4,
        /// The `purchase_limit` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        purchase_limit -> Int2,
        /// The `small_icon` column of the `props_malls` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        small_icon -> Varchar,
        /// The `gem_amounts` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        gem_amounts -> Int4,
        /// The `food_amounts` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        food_amounts -> Int4,
        /// The `wood_amounts` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        wood_amounts -> Int4,
        /// The `first_buy_handsel` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        first_buy_handsel -> Int4,
        /// The `late_buy_handsel` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        late_buy_handsel -> Int4,
        /// The `valid_period_day` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        valid_period_day -> Int2,
        /// The `mall_type` column of the `props_malls` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        mall_type -> Int2,
        /// The `modify_time` column of the `props_malls` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_malls` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_product_numbers` table.
    ///
    /// (Automatically generated by Diesel.)
    props_product_numbers (item_id) {
        /// The `item_id` column of the `props_product_numbers` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `product_number` column of the `props_product_numbers` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        product_number -> Varchar,
        /// The `platform_id` column of the `props_product_numbers` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        platform_id -> Int2,
        /// The `modify_time` column of the `props_product_numbers` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_product_numbers` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_resources_categorys` table.
    ///
    /// (Automatically generated by Diesel.)
    props_resources_categorys (item_id) {
        /// The `item_id` column of the `props_resources_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `rss_value` column of the `props_resources_categorys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        rss_value -> Int4,
        /// The `modify_time` column of the `props_resources_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_resources_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_speed_up_categorys` table.
    ///
    /// (Automatically generated by Diesel.)
    props_speed_up_categorys (item_id) {
        /// The `item_id` column of the `props_speed_up_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `speed_time` column of the `props_speed_up_categorys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        speed_time -> Int4,
        /// The `modify_time` column of the `props_speed_up_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_speed_up_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_starlight_sculpture_categorys` table.
    ///
    /// (Automatically generated by Diesel.)
    props_starlight_sculpture_categorys (item_id) {
        /// The `item_id` column of the `props_starlight_sculpture_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `exp_value` column of the `props_starlight_sculpture_categorys` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        exp_value -> Int2,
        /// The `probability_value` column of the `props_starlight_sculpture_categorys` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        probability_value -> Int2,
        /// The `modify_time` column of the `props_starlight_sculpture_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_starlight_sculpture_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `props_tome_of_knowledge_categorys` table.
    ///
    /// (Automatically generated by Diesel.)
    props_tome_of_knowledge_categorys (item_id) {
        /// The `item_id` column of the `props_tome_of_knowledge_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `exp_value` column of the `props_tome_of_knowledge_categorys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        exp_value -> Int8,
        /// The `modify_time` column of the `props_tome_of_knowledge_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `props_tome_of_knowledge_categorys` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `purchase_orders` table.
    ///
    /// (Automatically generated by Diesel.)
    purchase_orders (oid) {
        /// The `oid` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        oid -> Int8,
        /// The `obj_id` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        obj_id -> Int8,
        /// The `obj_type` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        obj_type -> Int2,
        /// The `uuid` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `hash` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        hash -> Varchar,
        /// The `product_number` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        product_number -> Varchar,
        /// The `pay_platform` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        pay_platform -> Int2,
        /// The `order_no` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        order_no -> Int8,
        /// The `status` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Int2,
        /// The `pay_time` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        pay_time -> Int8,
        /// The `price` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        price -> Float4,
        /// The `request_receipt_data` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        request_receipt_data -> Text,
        /// The `response_receipt_data` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        response_receipt_data -> Text,
        /// The `deleted_time` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_time -> Int8,
        /// The `modify_time` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `purchase_orders` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `server_lists` table.
    ///
    /// (Automatically generated by Diesel.)
    server_lists (slid) {
        /// The `slid` column of the `server_lists` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        slid -> Int8,
        /// The `name` column of the `server_lists` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `country_code` column of the `server_lists` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        country_code -> Varchar,
        /// The `area` column of the `server_lists` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        area -> Varchar,
        /// The `ip` column of the `server_lists` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        ip -> Varchar,
        /// The `port` column of the `server_lists` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        port -> Int2,
        /// The `server_type` column of the `server_lists` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        server_type -> Int2,
        /// The `state` column of the `server_lists` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        state -> Int2,
        /// The `modify_time` column of the `server_lists` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `server_lists` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `servers` table.
    ///
    /// (Automatically generated by Diesel.)
    servers (sid) {
        /// The `sid` column of the `servers` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        sid -> Int8,
        /// The `server_number` column of the `servers` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        server_number -> Int4,
        /// The `name` column of the `servers` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `person_count` column of the `servers` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        person_count -> Int4,
        /// The `modify_time` column of the `servers` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `servers` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `shops` table.
    ///
    /// (Automatically generated by Diesel.)
    shops (sid) {
        /// The `sid` column of the `shops` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        sid -> Int8,
        /// The `item_id` column of the `shops` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `bag_type` column of the `shops` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        bag_type -> Int2,
        /// The `sub_item_type` column of the `shops` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        sub_item_type -> Int2,
        /// The `order_value` column of the `shops` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        order_value -> Int8,
        /// The `gems_needed` column of the `shops` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        gems_needed -> Int4,
        /// The `modify_time` column of the `shops` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `shops` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `skill_fight_relateds` table.
    ///
    /// (Automatically generated by Diesel.)
    skill_fight_relateds (id) {
        /// The `id` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `obj_id` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        obj_id -> Int8,
        /// The `skill_id` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        skill_id -> Int8,
        /// The `cool_down` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        cool_down -> Int4,
        /// The `attack_power` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        attack_power -> Int4,
        /// The `mana_power` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        mana_power -> Int4,
        /// The `probability` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        probability -> Int2,
        /// The `level` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `level_experience` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        level_experience -> Int4,
        /// The `obj_type` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        obj_type -> Int2,
        /// The `modify_time` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `skill_fight_relateds` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `skills` table.
    ///
    /// (Automatically generated by Diesel.)
    skills (id) {
        /// The `id` column of the `skills` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `thumbnail` column of the `skills` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        thumbnail -> Varchar,
        /// The `skill_name` column of the `skills` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        skill_name -> Varchar,
        /// The `skill_description` column of the `skills` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        skill_description -> Varchar,
        /// The `model_path` column of the `skills` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        model_path -> Varchar,
        /// The `cool_down` column of the `skills` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        cool_down -> Int4,
        /// The `attack_power` column of the `skills` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        attack_power -> Int4,
        /// The `mana_power` column of the `skills` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        mana_power -> Int4,
        /// The `level` column of the `skills` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `level_experience` column of the `skills` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        level_experience -> Int4,
        /// The `modify_time` column of the `skills` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `skills` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `system_configs` table.
    ///
    /// (Automatically generated by Diesel.)
    system_configs (scid) {
        /// The `scid` column of the `system_configs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        scid -> Int8,
        /// The `key` column of the `system_configs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Varchar,
        /// The `value` column of the `system_configs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Varchar,
        /// The `modify_time` column of the `system_configs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `system_configs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_assets` table.
    ///
    /// (Automatically generated by Diesel.)
    user_assets (asid) {
        /// The `asid` column of the `user_assets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        asid -> Int8,
        /// The `uid` column of the `user_assets` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Int8,
        /// The `gold_amounts` column of the `user_assets` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        gold_amounts -> Int4,
        /// The `gem_amounts` column of the `user_assets` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        gem_amounts -> Int4,
        /// The `modify_time` column of the `user_assets` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_assets` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
        /// The `food_amounts` column of the `user_assets` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        food_amounts -> Int4,
        /// The `wood_amounts` column of the `user_assets` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        wood_amounts -> Int4,
        /// The `stone_amounts` column of the `user_assets` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        stone_amounts -> Int4,
    }
}

table! {
    /// Representation of the `user_buffs` table.
    ///
    /// (Automatically generated by Diesel.)
    user_buffs (bid) {
        /// The `bid` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        bid -> Int8,
        /// The `obj_id` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        obj_id -> Int8,
        /// The `obj_type` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        obj_type -> Int2,
        /// The `buff_id` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        buff_id -> Int8,
        /// The `buff_amounts` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        buff_amounts -> Int4,
        /// The `buff_category` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        buff_category -> Int2,
        /// The `buff_type` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        buff_type -> Int2,
        /// The `sub_buff_type` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        sub_buff_type -> Int2,
        /// The `is_show` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        is_show -> Int2,
        /// The `modify_time` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_buffs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_buy_props_mall_record_logs` table.
    ///
    /// (Automatically generated by Diesel.)
    user_buy_props_mall_record_logs (rid) {
        /// The `rid` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rid -> Int8,
        /// The `item_id` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `uuid` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `level` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `item_category` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        item_category -> Int2,
        /// The `purchase_limit` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        purchase_limit -> Int2,
        /// The `expire_time` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        expire_time -> Int8,
        /// The `latest_receive_time` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        latest_receive_time -> Int8,
        /// The `mall_type` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        mall_type -> Int2,
        /// The `modify_time` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_buy_props_mall_record_logs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_buy_props_mall_records` table.
    ///
    /// (Automatically generated by Diesel.)
    user_buy_props_mall_records (rid) {
        /// The `rid` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        rid -> Int8,
        /// The `item_id` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `uuid` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `level` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `item_category` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        item_category -> Int2,
        /// The `purchase_limit` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        purchase_limit -> Int2,
        /// The `expire_time` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        expire_time -> Int8,
        /// The `latest_receive_time` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        latest_receive_time -> Int8,
        /// The `mall_type` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        mall_type -> Int2,
        /// The `modify_time` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_buy_props_mall_records` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_counters` table.
    ///
    /// (Automatically generated by Diesel.)
    user_counters (id) {
        /// The `id` column of the `user_counters` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
    }
}

table! {
    /// Representation of the `user_equipments` table.
    ///
    /// (Automatically generated by Diesel.)
    user_equipments (id) {
        /// The `id` column of the `user_equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `eid` column of the `user_equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        eid -> Int8,
        /// The `uid` column of the `user_equipments` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Int8,
        /// The `modify_time` column of the `user_equipments` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_equipments` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_item_bags` table.
    ///
    /// (Automatically generated by Diesel.)
    user_item_bags (bid) {
        /// The `bid` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        bid -> Int8,
        /// The `uuid` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `item_id` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        item_id -> Int8,
        /// The `overlay_status` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        overlay_status -> Int2,
        /// The `bag_type` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        bag_type -> Int2,
        /// The `count` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        count -> Int4,
        /// The `order_value` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        order_value -> Int8,
        /// The `sub_item_type` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        sub_item_type -> Int2,
        /// The `modify_time` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_item_bags` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_link_accounts` table.
    ///
    /// (Automatically generated by Diesel.)
    user_link_accounts (lid) {
        /// The `lid` column of the `user_link_accounts` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        lid -> Int8,
        /// The `uuid` column of the `user_link_accounts` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `account_type` column of the `user_link_accounts` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        account_type -> Int2,
        /// The `modify_time` column of the `user_link_accounts` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_link_accounts` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_players` table.
    ///
    /// (Automatically generated by Diesel.)
    user_players (id) {
        /// The `id` column of the `user_players` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `pid` column of the `user_players` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        pid -> Int8,
        /// The `uid` column of the `user_players` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Int8,
        /// The `max_hp` column of the `user_players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        max_hp -> Int4,
        /// The `attack_power` column of the `user_players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        attack_power -> Int4,
        /// The `move_speed` column of the `user_players` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        move_speed -> Float4,
        /// The `max_mana` column of the `user_players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        max_mana -> Int4,
        /// The `defense` column of the `user_players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        defense -> Int4,
        /// The `level` column of the `user_players` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `star_level` column of the `user_players` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        star_level -> Int2,
        /// The `level_experience` column of the `user_players` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        level_experience -> Int4,
        /// The `is_default` column of the `user_players` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        is_default -> Int2,
        /// The `modify_time` column of the `user_players` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_players` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_player_tracks` table.
    ///
    /// (Automatically generated by Diesel.)
    user_player_tracks (tid) {
        /// The `tid` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        tid -> Int8,
        /// The `pid` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        pid -> Int8,
        /// The `uid` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Int8,
        /// The `rotaion_x` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        rotaion_x -> Float4,
        /// The `rotaion_y` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        rotaion_y -> Float4,
        /// The `rotaion_z` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        rotaion_z -> Float4,
        /// The `location_x` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        location_x -> Float4,
        /// The `location_y` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        location_y -> Float4,
        /// The `location_z` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        location_z -> Float4,
        /// The `modify_time` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_player_tracks` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_queues` table.
    ///
    /// (Automatically generated by Diesel.)
    user_queues (qid) {
        /// The `qid` column of the `user_queues` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        qid -> Int8,
        /// The `uuid` column of the `user_queues` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `building_queue` column of the `user_queues` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        building_queue -> Int2,
        /// The `research_queue` column of the `user_queues` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        research_queue -> Int2,
        /// The `training_queue` column of the `user_queues` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        training_queue -> Int2,
        /// The `healing_queue` column of the `user_queues` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        healing_queue -> Int2,
        /// The `armies_queue` column of the `user_queues` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        armies_queue -> Int2,
        /// The `scout_queue` column of the `user_queues` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        scout_queue -> Int2,
        /// The `modify_time` column of the `user_queues` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_queues` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (uuid) {
        /// The `uuid` column of the `users` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `uid` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Int4,
        /// The `name` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `avatar` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        avatar -> Varchar,
        /// The `login_days` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        login_days -> Int4,
        /// The `server_id` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        server_id -> Int4,
        /// The `modify_time` column of the `users` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `users` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
        /// The `action_points` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        action_points -> Int4,
        /// The `max_action_points` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        max_action_points -> Int4,
        /// The `action_points_latest_timestamp` column of the `users` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        action_points_latest_timestamp -> Int8,
        /// The `login_time` column of the `users` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        login_time -> Timestamp,
    }
}

table! {
    /// Representation of the `user_vips` table.
    ///
    /// (Automatically generated by Diesel.)
    user_vips (uvid) {
        /// The `uvid` column of the `user_vips` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uvid -> Int8,
        /// The `uuid` column of the `user_vips` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        uuid -> Int8,
        /// The `level` column of the `user_vips` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `vip_points` column of the `user_vips` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        vip_points -> Int4,
        /// The `daily_treasure_chests_time` column of the `user_vips` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        daily_treasure_chests_time -> Int8,
        /// The `free_everyday_treasure_chests_time` column of the `user_vips` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        free_everyday_treasure_chests_time -> Int8,
        /// The `special_privileges_treasure_chests_time` column of the `user_vips` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        special_privileges_treasure_chests_time -> Int8,
        /// The `modify_time` column of the `user_vips` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `user_vips` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `vip_buffs` table.
    ///
    /// (Automatically generated by Diesel.)
    vip_buffs (vbid) {
        /// The `vbid` column of the `vip_buffs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        vbid -> Int8,
        /// The `vlid` column of the `vip_buffs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        vlid -> Int8,
        /// The `buff_id` column of the `vip_buffs` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        buff_id -> Int8,
        /// The `is_new_mark` column of the `vip_buffs` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        is_new_mark -> Int2,
        /// The `modify_time` column of the `vip_buffs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `vip_buffs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `vip_daily_login_treasure_chests` table.
    ///
    /// (Automatically generated by Diesel.)
    vip_daily_login_treasure_chests (vdltc_id) {
        /// The `vdltc_id` column of the `vip_daily_login_treasure_chests` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        vdltc_id -> Int8,
        /// The `continuous_login_days` column of the `vip_daily_login_treasure_chests` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        continuous_login_days -> Int4,
        /// The `today_vip_points` column of the `vip_daily_login_treasure_chests` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        today_vip_points -> Int2,
        /// The `tomorrow_vip_points` column of the `vip_daily_login_treasure_chests` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        tomorrow_vip_points -> Int2,
        /// The `modify_time` column of the `vip_daily_login_treasure_chests` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `vip_daily_login_treasure_chests` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

table! {
    /// Representation of the `vip_levels` table.
    ///
    /// (Automatically generated by Diesel.)
    vip_levels (vlid) {
        /// The `vlid` column of the `vip_levels` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        vlid -> Int8,
        /// The `vip_points_needed` column of the `vip_levels` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        vip_points_needed -> Int4,
        /// The `level` column of the `vip_levels` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        level -> Int2,
        /// The `free_treasure_chest_item_id` column of the `vip_levels` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        free_treasure_chest_item_id -> Int8,
        /// The `pay_treasure_chest_item_id` column of the `vip_levels` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        pay_treasure_chest_item_id -> Int8,
        /// The `modify_time` column of the `vip_levels` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        modify_time -> Timestamp,
        /// The `created_time` column of the `vip_levels` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_time -> Timestamp,
    }
}

allow_tables_to_appear_in_same_query!(
    blacklists,
    buff_metadatas,
    chat_groups,
    chat_groups_uids,
    chat_messages,
    chat_user_unread_counts,
    enemys,
    equipment_kinds,
    equipments,
    friends,
    gem_relateds,
    gems,
    player_mount_equipments,
    players,
    props_action_points_categorys,
    props_fixed_treasure_chest_category_assets,
    props_fixed_treasure_chest_categorys,
    props_item_metadatas,
    props_key_categorys,
    props_mall_assets,
    props_malls,
    props_product_numbers,
    props_resources_categorys,
    props_speed_up_categorys,
    props_starlight_sculpture_categorys,
    props_tome_of_knowledge_categorys,
    purchase_orders,
    server_lists,
    servers,
    shops,
    skill_fight_relateds,
    skills,
    system_configs,
    user_assets,
    user_buffs,
    user_buy_props_mall_record_logs,
    user_buy_props_mall_records,
    user_counters,
    user_equipments,
    user_item_bags,
    user_link_accounts,
    user_players,
    user_player_tracks,
    user_queues,
    users,
    user_vips,
    vip_buffs,
    vip_daily_login_treasure_chests,
    vip_levels,
);
